//LISTA TODOS OS CPF'S
GET http://localhost:3000/usuario HTTP/1.1 
Content-Type: application/json 
### 
//FUNÇÃO PARA LISTAR INFORMAÇÕES DO CPF 
GET http://localhost:3000/usuario/1377626903 HTTP/1.1 
Content-Type: application/json 
###
//FUNÇÃO PARA CRIAR MAIS UM USUÁRIO
POST http://localhost:3000/usuario HTTP/1.1
Content-Type: application/json

{
    "cpf_user": "...",
    "nome_user": "...", 
    "email_user": "..."  
}
### 
//EDITAR INFORMAÇÕES DO USUARIO escolhido /usuario/...
PUT http://localhost:3000/usuario/2147483647 HTTP/1.1
Content-Type: application/json
 
{
    "nome_user": "yasmin cittadin",
    "email_user": "yasmin@icloud.com"
}
### 
//EDITAR INFORMAÇÕES DO USUARIO escolhido /usuario/... Altera Somente o CPF
PUT http://localhost:3000/usuario-cpf/1377626903 HTTP/1.1
Content-Type: application/json
 
{
    "cpf_user": "01377626903"
}
### 
//DELETAR O USUARIO escolhido /usuario/...
DELETE  http://localhost:3000/usuario/ HTTP/1.1
Content-Type: application/json



